server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver #数据库驱动包
    url: jdbc:mysql://localhost:3306/db2020?serverTimezone=UTC
    username: root
    password: root

eureka:
  client:
    register-with-eureka: true     #是否将自己注册进eureka-server
    fetch-registry: true           #是否从eureka-server抓取已有的注册信息，默认为true,集群必须设置为true才能配合ribbon使用负载均衡
    server-url:
      defaultZone: http://localhost:7001/eureka         #注册地址

mybatis:
  type-aliases-package: com.atwj.springcloud.entities
  mapper-locations: classpath:mapper/*.xml
