server:
  port: 8401

spring:
  application:
    name: nacos-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   #Nacos服务注册中心地址，需要注册进注册中心
    sentinel:
      transport:
        dashboard: localhost:8080    #配置Sentinel dashboar地址
        port: 8719      #默认8719端口，如果被占用会自动从8719开始依次+1扫描，知道找到未被占用的端口
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data_type: json
            rule-type: flow

management:
  endpoint:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true