server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: false     #是否将自己注册进eureka-server
    service-url:
      #defaultZone: http://localhost:7001/eureka         #注册地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
logging:
  level:   #fegin日志以什么级别监控哪个接口
    com.atwj.springcloud.service.PaymentFeignService: debug
